#!/bin/bash
find /var/www/html/streaming -name "*.ts" -type f -mmin +360 -exec rm -f {} \;
echo "Finished cleaning up streaming files."

# Note:
# run-parts does not like extensions such as .sh
# 
# For testing:
# run-parts -v /etc/cron.hourly
# http://10.0.0.227/streaming/index.m3u8
